const INSTRUCTORS_FOR_HIRE = [
  {
    id: "inst-ryan-cole",
    name: "Ryan Cole",
    description: "Reliable fundamentals coach for street lines.",
    wage: 180,
    sport: "Skateboarding",
    lessonSlots: 1,
    scoutRating: 58,
    coreRating: 3,
    variantRating: 3,
    determination: 42,
    switchRating: 4,
    ratings: {
      stall: 52,
      grind: 63,
      tech: 68,
      spin: 37,
      bigAir: 24,
    },
  },
  {
    id: "inst-anya-keller",
    name: "Anya Keller",
    description: "Technical rollerblading specialist with strong progression drills.",
    wage: 420,
    sport: "Rollerblading",
    lessonSlots: 3,
    scoutRating: 81,
    coreRating: 4,
    variantRating: 4,
    determination: 66,
    switchRating: 6,
    ratings: {
      stall: 72,
      grind: 86,
      tech: 88,
      spin: 64,
      bigAir: 39,
    },
  },
  {
    id: "inst-miles-hart",
    name: "Miles Hart",
    description: "Budget all-rounder for early academy sessions.",
    wage: 90,
    sport: "Skateboarding",
    lessonSlots: 2,
    scoutRating: 34,
    coreRating: 2,
    variantRating: 2,
    determination: 29,
    switchRating: 3,
    ratings: {
      stall: 31,
      grind: 38,
      tech: 35,
      spin: 26,
      bigAir: 18,
    },
  },
  {
    id: "inst-luca-moretti",
    name: "Luca Moretti",
    description: "High-end transition and spin mentor for advanced groups.",
    wage: 760,
    sport: "Rollerblading",
    lessonSlots: 2,
    scoutRating: 93,
    coreRating: 5,
    variantRating: 5,
    determination: 84,
    switchRating: 8,
    ratings: {
      stall: 79,
      grind: 82,
      tech: 75,
      spin: 92,
      bigAir: 74,
    },
  },
  {
    id: "inst-jade-kim",
    name: "Jade Kim",
    description: "Competition-focused skateboard coach with excellent scouting.",
    wage: 640,
    sport: "Skateboarding",
    lessonSlots: 4,
    scoutRating: 90,
    coreRating: 5,
    variantRating: 4,
    determination: 78,
    switchRating: 7,
    ratings: {
      stall: 70,
      grind: 91,
      tech: 88,
      spin: 73,
      bigAir: 67,
    },
  },
];

export default INSTRUCTORS_FOR_HIRE;
