const routesPieces = [
  {
    id: "route-padded-railings",
    name: "Padded Railings",
    purpose: "Use as a basic start or end piece.",
    type: "Route",
    routeType: ["Start", "End"],
    startPiece: true,
    endPiece: true,
    middlePiece: false,
    standalonePiece: false,
    size: { rows: 1, cols: 1 },
    marker: "PR",
    color: "#f97316",
    cost: 50,
    waitCapacity: 2,
    startingSpots: 2,
    dropSpeed: 1,
    speedCost: "All",
    maxEntranceSpeed: 2,
    trickOpportunities: 0,
    difficulty: {
      rollerblader: { stall: null, grind: null, tech: null, spin: null, bigAir: null },
      skateboarder: { stall: null, grind: null, tech: null, spin: null, bigAir: null },
    },
  },
  {
    id: "route-flatground",
    name: "Flatground",
    purpose: "Just concrete to pass over",
    type: "Route",
    routeType: ["Middle"],
    startPiece: false,
    endPiece: false,
    middlePiece: true,
    standalonePiece: false,
    size: { rows: 1, cols: 1 },
    marker: "FG",
    color: "#22c55e",
    cost: 50,
    waitCapacity: 0,
    startingSpots: 0,
    dropSpeed: 0,
    speedCost: 1,
    maxEntranceSpeed: 5,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: null, grind: null, tech: 1, spin: null, bigAir: null },
      skateboarder: { stall: null, grind: null, tech: 1, spin: null, bigAir: null },
    },
  },
  {
    id: "route-small-flatbank",
    name: "Small Flatbank",
    purpose: "A small flatbank for either side of the route",
    type: "Route",
    routeType: ["Start", "End"],
    startPiece: true,
    endPiece: true,
    middlePiece: false,
    standalonePiece: false,
    size: { rows: 1, cols: 1 },
    marker: "SFB",
    color: "#fb923c",
    cost: 100,
    waitCapacity: 2,
    startingSpots: 2,
    dropSpeed: 2,
    speedCost: "All",
    maxEntranceSpeed: 3,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: null, grind: null, tech: null, spin: 2, bigAir: null },
      skateboarder: { stall: null, grind: null, tech: 2, spin: null, bigAir: null },
    },
  },
  {
    id: "route-small-quarter-pipe",
    name: "Small Quarter Pipe",
    purpose: "A small quarter pipe for either side of the route",
    type: "Route",
    routeType: ["Start", "End"],
    startPiece: true,
    endPiece: true,
    middlePiece: false,
    standalonePiece: false,
    size: { rows: 1, cols: 1 },
    marker: "SQP",
    color: "#ea580c",
    cost: 100,
    waitCapacity: 1,
    startingSpots: 1,
    dropSpeed: 1,
    speedCost: "All",
    maxEntranceSpeed: 3,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: 1, grind: 2, tech: null, spin: null, bigAir: null },
      skateboarder: { stall: 1, grind: 2, tech: null, spin: null, bigAir: null },
    },
  },
  {
    id: "route-small-square-rail",
    name: "Small Square Rail",
    purpose: "Basic middle piece better for skateboards",
    type: "Route",
    routeType: ["Middle"],
    startPiece: false,
    endPiece: false,
    middlePiece: true,
    standalonePiece: false,
    size: { rows: 1, cols: 1 },
    marker: "SSR",
    color: "#10b981",
    cost: 100,
    waitCapacity: 0,
    startingSpots: 0,
    dropSpeed: 0,
    speedCost: 1,
    maxEntranceSpeed: 2,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: null, grind: 3, tech: null, spin: null, bigAir: null },
      skateboarder: { stall: null, grind: 1, tech: null, spin: null, bigAir: null },
    },
  },
  {
    id: "route-small-round-rail",
    name: "Small Round Rail",
    purpose: "Basic middle piece better for rollerblades",
    type: "Route",
    routeType: ["Middle"],
    startPiece: false,
    endPiece: false,
    middlePiece: true,
    standalonePiece: false,
    size: { rows: 1, cols: 1 },
    marker: "SRR",
    color: "#059669",
    cost: 100,
    waitCapacity: 0,
    startingSpots: 0,
    dropSpeed: 0,
    speedCost: 1,
    maxEntranceSpeed: 2,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: null, grind: 1, tech: null, spin: null, bigAir: null },
      skateboarder: { stall: null, grind: 3, tech: null, spin: null, bigAir: null },
    },
  },
  {
    id: "route-small-kicker",
    name: "Small Kicker",
    purpose: "Basic middle piece for introducing grabs and flips etc.",
    type: "Route",
    routeType: ["Middle"],
    startPiece: false,
    endPiece: false,
    middlePiece: true,
    standalonePiece: false,
    size: { rows: 1, cols: 1 },
    marker: "SK",
    color: "#16a34a",
    cost: 100,
    waitCapacity: 0,
    startingSpots: 0,
    dropSpeed: 0,
    speedCost: 1,
    maxEntranceSpeed: 2,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: null, grind: null, tech: null, spin: 2, bigAir: null },
      skateboarder: { stall: null, grind: null, tech: 2, spin: 2, bigAir: null },
    },
  },
  {
    id: "route-small-spine",
    name: "Small Spine",
    purpose: "A kind of better version of a kicker offering more trick types.",
    type: "Route",
    routeType: ["Middle"],
    startPiece: false,
    endPiece: false,
    middlePiece: true,
    standalonePiece: false,
    size: { rows: 1, cols: 1 },
    marker: "SSP",
    color: "#65a30d",
    cost: 150,
    waitCapacity: 0,
    startingSpots: 0,
    dropSpeed: 0,
    speedCost: 2,
    maxEntranceSpeed: 3,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: 2, grind: null, tech: null, spin: 3, bigAir: null },
      skateboarder: { stall: 2, grind: null, tech: 3, spin: null, bigAir: null },
    },
  },
  {
    id: "route-small-quarter-pipe-box",
    name: "Small Quarter Pipe With Box",
    purpose: "An end piece to try and get some good early scors for stalls.",
    type: "Route",
    routeType: ["End"],
    startPiece: false,
    endPiece: true,
    middlePiece: false,
    standalonePiece: false,
    size: { rows: 1, cols: 1 },
    marker: "SQB",
    color: "#dc2626",
    cost: 150,
    waitCapacity: 0,
    startingSpots: 0,
    dropSpeed: 0,
    speedCost: "All",
    maxEntranceSpeed: 3,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: 3, grind: 2, tech: null, spin: null, bigAir: null },
      skateboarder: { stall: 4, grind: 2, tech: null, spin: null, bigAir: null },
    },
  },
  {
    id: "route-small-grind-box-square",
    name: "Small Grind Box (Square Coping)",
    purpose: "Good for learning grinds on. Better for skateboards.",
    type: "Route",
    routeType: ["Middle"],
    startPiece: false,
    endPiece: false,
    middlePiece: true,
    standalonePiece: false,
    size: { rows: 1, cols: 1 },
    marker: "SGBS",
    color: "#15803d",
    cost: 100,
    waitCapacity: 0,
    startingSpots: 0,
    dropSpeed: 0,
    speedCost: 1,
    maxEntranceSpeed: 2,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: null, grind: 3, tech: 1, spin: null, bigAir: null },
      skateboarder: { stall: null, grind: 1, tech: 2, spin: null, bigAir: null },
    },
  },
  {
    id: "route-small-grind-box-round",
    name: "Small Grind Box (Round Coping)",
    purpose: "Good for learning grinds on. Better for rollerblades",
    type: "Route",
    routeType: ["Middle"],
    startPiece: false,
    endPiece: false,
    middlePiece: true,
    standalonePiece: false,
    size: { rows: 1, cols: 1 },
    marker: "SGBR",
    color: "#166534",
    cost: 100,
    waitCapacity: 0,
    startingSpots: 0,
    dropSpeed: 0,
    speedCost: 1,
    maxEntranceSpeed: 2,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: null, grind: 1, tech: 1, spin: null, bigAir: null },
      skateboarder: { stall: null, grind: 2, tech: 2, spin: null, bigAir: null },
    },
  },
  {
    id: "route-big-flatbank",
    name: "Big Flatbank",
    purpose: "Improved starting piece with more speed",
    type: "Route",
    routeType: ["Start", "End"],
    startPiece: true,
    endPiece: true,
    middlePiece: false,
    standalonePiece: false,
    size: { rows: 1, cols: 1 },
    marker: "BFB",
    color: "#f97316",
    cost: 500,
    waitCapacity: 2,
    startingSpots: 2,
    dropSpeed: 3,
    speedCost: "All",
    maxEntranceSpeed: 5,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: null, grind: null, tech: 3, spin: null, bigAir: null },
      skateboarder: { stall: null, grind: null, tech: 3, spin: null, bigAir: null },
    },
  },
  {
    id: "route-big-quarter-pipe",
    name: "Big Quarter Pipe",
    purpose: "A basic starting piece that is a better end piece than starting piece",
    type: "Route",
    routeType: ["Start", "End"],
    startPiece: true,
    endPiece: true,
    middlePiece: false,
    standalonePiece: false,
    size: { rows: 1, cols: 1 },
    marker: "BQP",
    color: "#ea580c",
    cost: 500,
    waitCapacity: 1,
    startingSpots: 1,
    dropSpeed: 2,
    speedCost: "All",
    maxEntranceSpeed: 4,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: 3, grind: 5, tech: null, spin: 5, bigAir: 5 },
      skateboarder: { stall: 4, grind: 6, tech: null, spin: 3, bigAir: 5 },
    },
  },
  {
    id: "route-bank-to-bank-box",
    name: "Bank to Bank Box",
    purpose: "A place to get some decent level tricks",
    type: "Route",
    routeType: ["Middle"],
    startPiece: false,
    endPiece: false,
    middlePiece: true,
    standalonePiece: false,
    size: { rows: 1, cols: 1 },
    marker: "BTB",
    color: "#22c55e",
    cost: 300,
    waitCapacity: 0,
    startingSpots: 0,
    dropSpeed: 0,
    speedCost: 2,
    maxEntranceSpeed: 3,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: null, grind: null, tech: 3, spin: 4, bigAir: null },
      skateboarder: { stall: null, grind: null, tech: 3, spin: 3, bigAir: null },
    },
  },
  {
    id: "route-bank-to-bank-box-square-rail",
    name: "Bank to Bank Box with Square Rail",
    purpose: "A place to get some decent level grind tricks, better for skateboards",
    type: "Route",
    routeType: ["Middle"],
    startPiece: false,
    endPiece: false,
    middlePiece: true,
    standalonePiece: false,
    size: { rows: 1, cols: 1 },
    marker: "BTSR",
    color: "#16a34a",
    cost: 400,
    waitCapacity: 0,
    startingSpots: 0,
    dropSpeed: 0,
    speedCost: 2,
    maxEntranceSpeed: 3,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: null, grind: 6, tech: null, spin: null, bigAir: null },
      skateboarder: { stall: null, grind: 4, tech: null, spin: null, bigAir: null },
    },
  },
  {
    id: "route-bank-to-bank-box-round-rail",
    name: "Bank to Bank Box with Round Rail",
    purpose: "A place to get some decent level grind tricks, better for rollerblades",
    type: "Route",
    routeType: ["Middle"],
    startPiece: false,
    endPiece: false,
    middlePiece: true,
    standalonePiece: false,
    size: { rows: 1, cols: 1 },
    marker: "BTRR",
    color: "#15803d",
    cost: 400,
    waitCapacity: 0,
    startingSpots: 0,
    dropSpeed: 0,
    speedCost: 2,
    maxEntranceSpeed: 3,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: null, grind: 4, tech: null, spin: null, bigAir: null },
      skateboarder: { stall: null, grind: 6, tech: null, spin: null, bigAir: null },
    },
  },
  {
    id: "route-bank-to-bank-box-planter-square",
    name: "Bank to Bank Box with Planter (Square Coping)",
    purpose: "A place to get some decent level grind and tech tricks, better for skateboards",
    type: "Route",
    routeType: ["Middle"],
    startPiece: false,
    endPiece: false,
    middlePiece: true,
    standalonePiece: false,
    size: { rows: 1, cols: 1 },
    marker: "BTPS",
    color: "#65a30d",
    cost: 400,
    waitCapacity: 0,
    startingSpots: 0,
    dropSpeed: 0,
    speedCost: 2,
    maxEntranceSpeed: 3,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: null, grind: 5, tech: 3, spin: 2, bigAir: null },
      skateboarder: { stall: null, grind: 3, tech: 3, spin: 3, bigAir: null },
    },
  },
  {
    id: "route-bank-to-bank-box-planter-round",
    name: "Bank to Bank Box with Planter (Round Coping)",
    purpose: "A place to get some decent level grind and tech tricks, better for rollerblades",
    type: "Route",
    routeType: ["Middle"],
    startPiece: false,
    endPiece: false,
    middlePiece: true,
    standalonePiece: false,
    size: { rows: 1, cols: 1 },
    marker: "BTPR",
    color: "#4d7c0f",
    cost: 400,
    waitCapacity: 0,
    startingSpots: 0,
    dropSpeed: 0,
    speedCost: 2,
    maxEntranceSpeed: 3,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: null, grind: 3, tech: 3, spin: 2, bigAir: null },
      skateboarder: { stall: null, grind: 5, tech: 3, spin: 3, bigAir: null },
    },
  },
  {
    id: "route-medium-spine",
    name: "Medium Spine",
    purpose: "A harder spine that needs more speed",
    type: "Route",
    routeType: ["Middle"],
    startPiece: false,
    endPiece: false,
    middlePiece: true,
    standalonePiece: false,
    size: { rows: 1, cols: 1 },
    marker: "MSP",
    color: "#84cc16",
    cost: 500,
    waitCapacity: 0,
    startingSpots: 0,
    dropSpeed: 0,
    speedCost: 3,
    maxEntranceSpeed: 4,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: 5, grind: null, tech: null, spin: 4, bigAir: 8 },
      skateboarder: { stall: 5, grind: null, tech: 7, spin: 5, bigAir: 8 },
    },
  },
  {
    id: "route-small-jump-box",
    name: "Small Jump Box",
    purpose: "Kind of like a spine but harder with no grinding or stalls",
    type: "Route",
    routeType: ["Middle"],
    startPiece: false,
    endPiece: false,
    middlePiece: true,
    standalonePiece: false,
    size: { rows: 1, cols: 1 },
    marker: "SJB",
    color: "#a3e635",
    cost: 500,
    waitCapacity: 0,
    startingSpots: 0,
    dropSpeed: 0,
    speedCost: 3,
    maxEntranceSpeed: 4,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: null, grind: null, tech: 5, spin: 6, bigAir: 7 },
      skateboarder: { stall: null, grind: null, tech: 7, spin: 5, bigAir: 7 },
    },
  },
  {
    id: "route-big-quarter-pipe-box",
    name: "Big Quarter Pipe With Box",
    purpose: "An end piece for some decent stalls",
    type: "Route",
    routeType: ["End"],
    startPiece: false,
    endPiece: true,
    middlePiece: false,
    standalonePiece: false,
    size: { rows: 1, cols: 1 },
    marker: "BQB",
    color: "#b91c1c",
    cost: 500,
    waitCapacity: 0,
    startingSpots: 0,
    dropSpeed: 0,
    speedCost: "All",
    maxEntranceSpeed: 5,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: 5, grind: 7, tech: null, spin: 5, bigAir: null },
      skateboarder: { stall: 6, grind: 8, tech: null, spin: 3, bigAir: null },
    },
  },
  {
    id: "route-medium-london-gap",
    name: "Medium London Gap",
    purpose: "For the decent tech tricks",
    type: "Route",
    routeType: ["End"],
    startPiece: false,
    endPiece: true,
    middlePiece: false,
    standalonePiece: false,
    size: { rows: 1, cols: 1 },
    marker: "MLG",
    color: "#991b1b",
    cost: 500,
    waitCapacity: 0,
    startingSpots: 0,
    dropSpeed: 0,
    speedCost: "All",
    maxEntranceSpeed: 3,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: null, grind: null, tech: 3, spin: 3, bigAir: null },
      skateboarder: { stall: null, grind: null, tech: 5, spin: 5, bigAir: null },
    },
  },
];

export default routesPieces;
