const standalonePieces = [
  {
    id: "standalone-small-mini-ramp",
    name: "Small Mini Ramp",
    purpose:
      "First standalone piece for early capacity and consistent income.",
    type: "Standalone",
    startPiece: false,
    endPiece: false,
    middlePiece: false,
    standalonePiece: true,
    size: { rows: 2, cols: 2 },
    marker: "SMR",
    color: "#0ea5e9",
    cost: 300,
    waitCapacity: 2,
    startingSpots: 2,
    dropSpeed: 0,
    speedCost: null,
    maxEntranceSpeed: null,
    trickOpportunities: 2,
    difficulty: {
      rollerblader: { stall: 1, grind: 1, tech: null, spin: 1, bigAir: null },
      skateboarder: { stall: 1, grind: 1, flip: 3, grab: null, bigAir: null },
    },
  },
  {
    id: "standalone-8-stair-set",
    name: "8 Stair Set",
    purpose: "Standalone with more capacity but one trick opportunity each run.",
    type: "Standalone",
    startPiece: false,
    endPiece: false,
    middlePiece: false,
    standalonePiece: true,
    size: { rows: 2, cols: 1 },
    marker: "8SS",
    color: "#0284c7",
    cost: 500,
    waitCapacity: 3,
    startingSpots: 3,
    dropSpeed: 0,
    speedCost: null,
    maxEntranceSpeed: null,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: null, grind: null, tech: null, spin: 4, bigAir: null },
      skateboarder: { stall: null, grind: null, flip: 4, grab: null, bigAir: null },
    },
  },
  {
    id: "standalone-6-stair-set-handrail",
    name: "6 Stair Set with Handrail",
    purpose: "Standalone with higher capacity and rail-focused tricks.",
    type: "Standalone",
    startPiece: false,
    endPiece: false,
    middlePiece: false,
    standalonePiece: true,
    size: { rows: 2, cols: 1 },
    marker: "6SH",
    color: "#0369a1",
    cost: 500,
    waitCapacity: 3,
    startingSpots: 3,
    dropSpeed: 0,
    speedCost: null,
    maxEntranceSpeed: null,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: null, grind: 4, tech: null, spin: 4, bigAir: null },
      skateboarder: { stall: null, grind: 6, flip: 6, grab: null, bigAir: null },
    },
  },
  {
    id: "standalone-mini-ramp",
    name: "Mini Ramp",
    purpose: "Larger mini ramp variant with stronger grind potential.",
    type: "Standalone",
    startPiece: false,
    endPiece: false,
    middlePiece: false,
    standalonePiece: true,
    size: { rows: 3, cols: 2 },
    marker: "MRP",
    color: "#075985",
    cost: 600,
    waitCapacity: 2,
    startingSpots: 2,
    dropSpeed: 0,
    speedCost: null,
    maxEntranceSpeed: null,
    trickOpportunities: 2,
    difficulty: {
      rollerblader: { stall: 3, grind: 3, tech: null, spin: 3, bigAir: null },
      skateboarder: { stall: 3, grind: 3, flip: 6, grab: null, bigAir: null },
    },
  },
];

export default standalonePieces;
