const standalonePieces = [
  {
    id: "standalone-small-mini-ramp",
    name: "Small Mini Ramp",
    purpose:
      "The first standalone piece, the player will be prompted to place one as part of a tutorial next to their first run. Will be good for early capacity and some constant income",
    type: "Standalone",
    startPiece: false,
    endPiece: false,
    middlePiece: false,
    standalonePiece: true,
    size: { rows: 2, cols: 2 },
    marker: "SMR",
    color: "#0ea5e9",
    cost: 300,
    waitCapacity: 2,
    startingSpots: 2,
    dropSpeed: 0,
    speedCost: null,
    maxEntranceSpeed: null,
    trickOpportunities: 2,
    difficulty: {
      rollerblader: { stall: 1, grind: 1, tech: null, spin: null, bigAir: null },
      skateboarder: { stall: 1, grind: 1, tech: 1, spin: null, bigAir: null },
    },
  },
  {
    id: "standalone-8-stair-set",
    name: "8 Stair Set",
    purpose: "Standalone with more capacity but only 1 trick oppotunity each",
    type: "Standalone",
    startPiece: false,
    endPiece: false,
    middlePiece: false,
    standalonePiece: true,
    size: { rows: 2, cols: 1 },
    marker: "8SS",
    color: "#0284c7",
    cost: 500,
    waitCapacity: 3,
    startingSpots: 3,
    dropSpeed: 0,
    speedCost: null,
    maxEntranceSpeed: null,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: null, grind: null, tech: null, spin: 4, bigAir: null },
      skateboarder: { stall: null, grind: null, tech: 4, spin: null, bigAir: null },
    },
  },
  {
    id: "standalone-6-stair-set-handrail",
    name: "6 Stair Set with Handrail",
    purpose: "Standalone with more capacity but only 1 trick oppotunity each",
    type: "Standalone",
    startPiece: false,
    endPiece: false,
    middlePiece: false,
    standalonePiece: true,
    size: { rows: 2, cols: 1 },
    marker: "6SH",
    color: "#0369a1",
    cost: 500,
    waitCapacity: 3,
    startingSpots: 3,
    dropSpeed: 0,
    speedCost: null,
    maxEntranceSpeed: null,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: null, grind: 4, tech: null, spin: 4, bigAir: null },
      skateboarder: { stall: null, grind: 6, tech: 6, spin: null, bigAir: null },
    },
  },
  {
    id: "standalone-9-stair-set-handrail",
    name: "9 Stair Set with Handrail",
    purpose: "Standalone with more capacity but only 1 trick oppotunity each",
    type: "Standalone",
    startPiece: false,
    endPiece: false,
    middlePiece: false,
    standalonePiece: true,
    size: { rows: 2, cols: 1 },
    marker: "9SH",
    color: "#075985",
    cost: 500,
    waitCapacity: 3,
    startingSpots: 3,
    dropSpeed: 0,
    speedCost: null,
    maxEntranceSpeed: null,
    trickOpportunities: 1,
    difficulty: {
      rollerblader: { stall: null, grind: 8, tech: null, spin: 7, bigAir: null },
      skateboarder: { stall: null, grind: 9, tech: 8, spin: null, bigAir: null },
    },
  },
  {
    id: "standalone-vert-ramp",
    name: "Vert Ramp",
    purpose: "Big ramp for big tricks.",
    type: "Standalone",
    startPiece: false,
    endPiece: false,
    middlePiece: false,
    standalonePiece: true,
    size: { rows: 3, cols: 3 },
    marker: "VR",
    color: "#1d4ed8",
    cost: 1000,
    waitCapacity: 3,
    startingSpots: 3,
    dropSpeed: 0,
    speedCost: null,
    maxEntranceSpeed: null,
    trickOpportunities: 2,
    difficulty: {
      rollerblader: { stall: 5, grind: 6, tech: null, spin: 7, bigAir: 9 },
      skateboarder: { stall: 6, grind: 7, tech: null, spin: 7, bigAir: 9 },
    },
  },
  {
    id: "standalone-mini-ramp",
    name: "Mini Ramp",
    purpose: "Bigger version of a mini ramp, better for grinding",
    type: "Standalone",
    startPiece: false,
    endPiece: false,
    middlePiece: false,
    standalonePiece: true,
    size: { rows: 2, cols: 3 },
    marker: "MRP",
    color: "#0c4a6e",
    cost: 600,
    waitCapacity: 2,
    startingSpots: 2,
    dropSpeed: 0,
    speedCost: null,
    maxEntranceSpeed: null,
    trickOpportunities: 2,
    difficulty: {
      rollerblader: { stall: 3, grind: 3, tech: null, spin: 3, bigAir: null },
      skateboarder: { stall: 3, grind: 3, tech: 6, spin: null, bigAir: null },
    },
  },
];

export default standalonePieces;
